import type { ProjectState } from "./types";

const now = new Date().toISOString();

export const seedState: ProjectState = {
  project: {
    id: "project_atlas",
    name: "Campus Skill Exchange",
    shortName: "Atlas",
    audience: "Students who want to teach or learn practical skills from peers on campus.",
    problem: "Useful peer knowledge is scattered across group chats and informal networks, so students cannot reliably find a person, time, or place to learn.",
    definitionOfDone: [
      "Critical user journey works in preview",
      "Acceptance criteria have linked evidence",
      "Another teammate has reviewed the feature",
      "No real personal data or exposed secrets",
      "A learner can explain the change without the agent",
    ],
    safetyConstraints: ["Synthetic profiles only", "No payments", "No production secrets"],
  },
  currentMemberId: "member_maya",
  members: [
    { id: "member_maya", name: "Maya Chen", initials: "MC", role: "product" },
    { id: "member_amir", name: "Amir Rahman", initials: "AR", role: "verification" },
    { id: "member_noa", name: "Noa Williams", initials: "NW", role: "integration" },
  ],
  features: [
    {
      id: "feature_profiles",
      title: "Skill profiles",
      userStory: "As a student, I can describe one skill I can teach and one I want to learn.",
      acceptanceCriteria: ["Profile displays both skill types", "Empty state explains what to add", "Only synthetic demo data is stored"],
      dependencies: [],
      status: "done",
      ownerId: "member_noa",
      risk: "medium",
      updatedAt: now,
    },
    {
      id: "feature_search",
      title: "Find a peer",
      userStory: "As a student, I can filter profiles by skill and availability.",
      acceptanceCriteria: ["Search returns matching profiles", "No-result state offers recovery", "Filter state survives refresh"],
      dependencies: ["feature_profiles"],
      status: "active",
      ownerId: "member_maya",
      risk: "low",
      updatedAt: now,
    },
    {
      id: "feature_request",
      title: "Request a session",
      userStory: "As a student, I can request a learning session without exposing private contact information.",
      acceptanceCriteria: ["Request includes skill and proposed window", "Recipient can accept or decline", "Contact details remain hidden"],
      dependencies: ["feature_profiles", "feature_search"],
      status: "review",
      ownerId: "member_amir",
      risk: "high",
      updatedAt: now,
    },
    {
      id: "feature_reflection",
      title: "Learning reflection",
      userStory: "As a student, I can record what I learned after a session.",
      acceptanceCriteria: ["Reflection accepts short text", "Learner can revise before publishing", "Private-by-default state is visible"],
      dependencies: ["feature_request"],
      status: "queued",
      risk: "medium",
      updatedAt: now,
    },
  ],
  sessions: [
    {
      id: "session_search",
      featureId: "feature_search",
      memberId: "member_maya",
      plan: "Connect the filter controls to URL state, then verify refresh behavior and the no-result case.",
      expectedEvidence: "Preview URL, refresh test, and screenshot of the no-result state.",
      startedAt: now,
    },
  ],
  decisions: [
    {
      id: "decision_private_contact",
      featureId: "feature_request",
      memberId: "member_amir",
      decision: "Keep all contact details hidden until both learners accept a request.",
      rationale: "The demo should teach consent and data minimization rather than reproduce an unsafe directory.",
      alternatives: "Show university email immediately; use an external messaging link.",
      affectedComponents: ["requests", "profiles", "permissions"],
      createdAt: now,
    },
  ],
  evidence: [
    {
      id: "evidence_profile_test",
      featureId: "feature_profiles",
      memberId: "member_noa",
      type: "test",
      title: "Profile empty-state test",
      result: "pass",
      details: "Verified that a new profile explains both required skill fields before saving.",
      createdAt: now,
    },
    {
      id: "evidence_request_preview",
      featureId: "feature_request",
      memberId: "member_amir",
      type: "preview",
      title: "Consent flow preview",
      result: "inconclusive",
      details: "Happy path works. Permission test for declined requests is still missing.",
      createdAt: now,
    },
  ],
  reviews: [
    {
      id: "review_profiles",
      featureId: "feature_profiles",
      requesterId: "member_noa",
      reviewerId: "member_amir",
      status: "accepted",
      notes: "Accepted after the empty-state evidence was attached.",
      createdAt: now,
    },
    {
      id: "review_request",
      featureId: "feature_request",
      requesterId: "member_amir",
      reviewerId: "member_maya",
      status: "changes_requested",
      notes: "Show that a declined request cannot reveal contact details.",
      createdAt: now,
    },
  ],
  handoffs: [
    {
      id: "handoff_profiles",
      featureId: "feature_profiles",
      memberId: "member_noa",
      intent: "Make profile intent legible before introducing matching.",
      changes: "Added teach/learn fields, validation, and a guided empty state.",
      evidenceSummary: "Empty-state test passes and peer review is accepted.",
      uncertainty: "We have not tested long multilingual skill names.",
      nextAction: "Use the profile schema as the source for search filters.",
      createdAt: now,
    },
  ],
};
